### PR TITLE
Add suport to handle message reads event

### PR DESCRIPTION
**Pull request by luizcarvalho**

### CODE REVIEW

**Comment by mgomes** [comment]
@luizcarvalho thanks for the PR! Does this need a corresponding PR for `stealth` to add the `read` attribute to a `ServiceMessage`? Or should we be setting the payload to `_read` or something like that?

**Comment by luizcarvalho** [comment]
Hello @mgomes , this PR no need any change in `stealth`. I use same strategy usend in [stealth-mixpanel](https://github.com/hellostealth/stealth-mixpanel/blob/master/lib/stealth-mixpanel/state_transitions.rb) and add `read` attribute using `prepend` module into `ServiceMessage` and works as well for my application, maybe works for all.

**Comment by mgomes** [comment]
Ah, I see. Merging now and then I will release a new version after I update the README.

Thanks again! ❤️

**Comment by luizcarvalho** [comment]
My pleasure 🤩🤩🤩

Thank you!!

**Pull request merged**
